import { readFile, writeFile } from 'node:fs/promises';
const root = new URL('../', import.meta.url);
const schema = await readFile(new URL('shared/schema.js', root), 'utf8');
const importer = await readFile(new URL('figma/importer.js', root), 'utf8');
const ui = await readFile(new URL('figma/ui.template.html', root), 'utf8');
const bridgeUI = await readFile(new URL('figma/bridge-ui.js', root), 'utf8');
await writeFile(new URL('figma/code.js', root), '// Generated by scripts/build.mjs\n' + schema + '\n' + importer);
await writeFile(new URL('figma/ui.html', root), ui.replace('/* SCHEMA */', () => schema).replace('/* BRIDGE_UI */', () => bridgeUI));
console.log('Built figma/code.js and figma/ui.html');
